// twitter always uses exactly this one
export const _bearer =
	'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA';
// if wrong, will be generated by script
export const _authToken = '0a0205c12365f6355613b6f2d486d474b6';
// if wrong, will be generated by script
export const _csrfToken = 'b8caffd5c8d32770003427c21416baa0daff78c';
